import React from "react";
import { BarChart3, TrendingUp, Users, DollarSign, Calendar, Target } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const Analytics = () => {
  const metrics = [
    {
      title: "Total Revenue",
      value: "$847,200",
      change: "+12.5%",
      icon: DollarSign,
      color: "text-green-600",
      bgColor: "bg-green-100"
    },
    {
      title: "Conversion Rate", 
      value: "24.8%",
      change: "+3.2%",
      icon: Target,
      color: "text-blue-600",
      bgColor: "bg-blue-100"
    },
    {
      title: "Leads Generated",
      value: "1,247",
      change: "+18.7%",
      icon: Users,
      color: "text-purple-600",
      bgColor: "bg-purple-100"
    },
    {
      title: "Avatar Interactions",
      value: "3,892",
      change: "+25.1%",
      icon: BarChart3,
      color: "text-orange-600",
      bgColor: "bg-orange-100"
    }
  ];

  const avatarPerformance = [
    { name: "Sarah Johnson", leads: 127, conversions: 31, revenue: "$287,500" },
    { name: "Michael Chen", leads: 89, conversions: 22, revenue: "$198,400" },
    { name: "Emily Rodriguez", leads: 156, conversions: 38, revenue: "$361,300" }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="flex items-center justify-between px-6 py-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Analytics</h1>
            <p className="text-gray-600">Track your performance and revenue</p>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="flex items-center gap-1">
              <Calendar size={12} />
              Last 30 days
            </Badge>
          </div>
        </div>
      </header>

      <div className="p-6 space-y-6">
        {/* Key Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {metrics.map((metric, index) => {
            const Icon = metric.icon;
            return (
              <Card key={index}>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium text-gray-600">
                    {metric.title}
                  </CardTitle>
                  <div className={`p-2 rounded-full ${metric.bgColor}`}>
                    <Icon className={`h-4 w-4 ${metric.color}`} />
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{metric.value}</div>
                  <div className="flex items-center mt-1">
                    <TrendingUp size={12} className="text-green-600 mr-1" />
                    <span className="text-xs text-green-600">{metric.change}</span>
                    <span className="text-xs text-gray-500 ml-1">vs last month</span>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Revenue Chart */}
          <Card>
            <CardHeader>
              <CardTitle>Revenue Over Time</CardTitle>
              <CardDescription>Monthly revenue generated by avatars</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-64 flex items-center justify-center bg-gray-100 rounded-lg">
                <div className="text-center">
                  <BarChart3 size={48} className="text-gray-400 mx-auto mb-2" />
                  <p className="text-gray-500">Revenue chart would go here</p>
                  <p className="text-sm text-gray-400">Integration with charting library needed</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Conversion Funnel */}
          <Card>
            <CardHeader>
              <CardTitle>Conversion Funnel</CardTitle>
              <CardDescription>Lead progression through sales stages</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Website Visitors</span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 bg-gray-200 rounded-full h-2">
                      <div className="bg-blue-600 h-2 rounded-full w-full"></div>
                    </div>
                    <span className="text-sm">12,847</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Avatar Interactions</span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 bg-gray-200 rounded-full h-2">
                      <div className="bg-blue-600 h-2 rounded-full w-4/5"></div>
                    </div>
                    <span className="text-sm">3,892</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Qualified Leads</span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 bg-gray-200 rounded-full h-2">
                      <div className="bg-blue-600 h-2 rounded-full w-3/5"></div>
                    </div>
                    <span className="text-sm">1,247</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Conversions</span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 bg-gray-200 rounded-full h-2">
                      <div className="bg-green-600 h-2 rounded-full w-1/4"></div>
                    </div>
                    <span className="text-sm">309</span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Avatar Performance Table */}
        <Card>
          <CardHeader>
            <CardTitle>Avatar Performance</CardTitle>
            <CardDescription>Individual avatar statistics and revenue attribution</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Avatar</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Leads</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Conversions</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Conversion Rate</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Revenue</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Commission</th>
                  </tr>
                </thead>
                <tbody>
                  {avatarPerformance.map((avatar, index) => {
                    const conversionRate = ((avatar.conversions / avatar.leads) * 100).toFixed(1);
                    const commission = (parseInt(avatar.revenue.replace(/[$,]/g, '')) * 0.01).toLocaleString();
                    return (
                      <tr key={index} className="border-b hover:bg-gray-50">
                        <td className="py-3 px-4 font-medium">{avatar.name}</td>
                        <td className="py-3 px-4">{avatar.leads}</td>
                        <td className="py-3 px-4">{avatar.conversions}</td>
                        <td className="py-3 px-4">
                          <Badge variant="secondary">{conversionRate}%</Badge>
                        </td>
                        <td className="py-3 px-4 font-medium text-green-600">{avatar.revenue}</td>
                        <td className="py-3 px-4 text-blue-600">${commission}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Analytics;